require('dotenv').config();
const express=require('express');
const path=require('path');
const crypto=require('crypto');
const bcrypt=require('bcryptjs');
const Database=require('better-sqlite3');
const helmet=require('helmet');
const compression=require('compression');
const rateLimit=require('express-rate-limit');

const app=express();
const PORT=Number(process.env.PORT||3000);
const SECRET=process.env.SESSION_SECRET;
const ADMIN_USER=process.env.ADMIN_USERNAME;
const ADMIN_PASS=process.env.ADMIN_PASSWORD;
if(!SECRET||!ADMIN_USER||!ADMIN_PASS){console.error('Missing SESSION_SECRET, ADMIN_USERNAME or ADMIN_PASSWORD');process.exit(1);}
const db=new Database(path.join(__dirname,'data.sqlite'));
db.pragma('journal_mode = WAL');
db.pragma('foreign_keys = ON');
db.exec(`
CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,slug TEXT UNIQUE NOT NULL,image TEXT DEFAULT '',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,size TEXT NOT NULL,category_id INTEGER NOT NULL,description TEXT DEFAULT '',icon TEXT DEFAULT '🛒',price INTEGER NOT NULL CHECK(price>=0),stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0),discount INTEGER NOT NULL DEFAULT 0 CHECK(discount BETWEEN 0 AND 100),image TEXT DEFAULT '',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(category_id) REFERENCES categories(id));
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,admin_id INTEGER NOT NULL,expires_at INTEGER NOT NULL,FOREIGN KEY(admin_id) REFERENCES admins(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,order_no TEXT UNIQUE NOT NULL,customer_name TEXT NOT NULL,phone TEXT NOT NULL,address TEXT NOT NULL,city TEXT NOT NULL,notes TEXT DEFAULT '',subtotal INTEGER NOT NULL,discount INTEGER NOT NULL,delivery_fee INTEGER NOT NULL,total INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'Pending',payment_method TEXT NOT NULL DEFAULT 'Cash on Delivery',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,product_id INTEGER NOT NULL,product_name TEXT NOT NULL,size TEXT NOT NULL,unit_price INTEGER NOT NULL,quantity INTEGER NOT NULL CHECK(quantity>0),line_total INTEGER NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
`);
if(!db.prepare('SELECT id FROM admins WHERE username=?').get(ADMIN_USER)) db.prepare('INSERT INTO admins(username,password_hash) VALUES(?,?)').run(ADMIN_USER,bcrypt.hashSync(ADMIN_PASS,12));
const catSeed=[['Rice & Grains','rice-grains','🍚'],['Dhal & Pulses','dhal-pulses','🫘'],['Flour & Baking','flour-baking','🌾'],['Cooking Oils','cooking-oils','🫗'],['Milk & Dairy','milk-dairy','🥛'],['Beverages','beverages','🍵'],['Biscuits & Snacks','biscuits-snacks','🍪'],['Vegetables','vegetables','🥕'],['Fruits','fruits','🍌'],['Household','household','🧽'],['Personal Care','personal-care','🧼']];
const addCat=db.prepare('INSERT OR IGNORE INTO categories(name,slug,image) VALUES(?,?,?)');catSeed.forEach(c=>addCat.run(...c));
if(db.prepare('SELECT COUNT(*) n FROM products').get().n===0){const ids=Object.fromEntries(db.prepare('SELECT id,name FROM categories').all().map(x=>[x.name,x.id]));const rows=[['Nadu Rice','1 kg','Rice & Grains','Premium everyday rice.',230,30,0,'🍚'],['Samba Rice','1 kg','Rice & Grains','Sri Lankan samba rice.',240,30,0,'🍚'],['Red Dhal','1 kg','Dhal & Pulses','Everyday red lentils.',320,25,0,'🫘'],['Wheat Flour','1 kg','Flour & Baking','All-purpose wheat flour.',250,20,0,'🌾'],['Coconut Oil','1 L','Cooking Oils','Pure cooking oil.',970,15,0,'🫗'],['Milk Powder','400 g','Milk & Dairy','Family milk powder pack.',1200,12,0,'🥛'],['Ceylon Tea','200 g','Beverages','Fragrant Ceylon tea.',450,20,0,'🍵'],['Cream Crackers','500 g','Biscuits & Snacks','Crispy crackers.',650,18,0,'🍪'],['Carrot','1 kg','Vegetables','Fresh carrots.',400,20,0,'🥕'],['Potato','1 kg','Vegetables','Fresh potatoes.',450,25,0,'🥔'],['Big Onion','1 kg','Vegetables','Fresh big onions.',350,20,0,'🧅'],['Banana','1 kg','Fruits','Fresh bananas.',300,20,0,'🍌'],['Dishwash Liquid','500 ml','Household','Everyday dishwashing liquid.',650,10,0,'🧽'],['Bath Soap','100 g','Personal Care','Daily personal care soap.',250,15,0,'🧼']];const ins=db.prepare('INSERT INTO products(name,size,category_id,description,price,stock,discount,icon) VALUES(?,?,?,?,?,?,?,?)');rows.forEach(r=>ins.run(r[0],r[1],ids[r[2]],r[3],r[4],r[5],r[6],r[7]));}
app.use(helmet({contentSecurityPolicy:false}));app.use(compression());app.use(express.json({limit:'100kb'}));app.use(express.urlencoded({extended:false,limit:'20kb'}));app.use(express.static(path.join(__dirname,'public'),{index:'index.html',maxAge:'1h'}));
const loginLimiter=rateLimit({windowMs:15*60*1000,limit:10,standardHeaders:true,legacyHeaders:false});const apiLimiter=rateLimit({windowMs:60*1000,limit:180,standardHeaders:true,legacyHeaders:false});
const secureCookie = process.env.NODE_ENV === 'production' ? '; Secure' : '';
const sha=v=>crypto.createHash('sha256').update(v).digest('hex');
const sign=v=>v+'.'+crypto.createHmac('sha256',SECRET).update(v).digest('hex');
function verify(v){if(!v)return null;const p=v.split('.');if(p.length!==2)return null;const e=crypto.createHmac('sha256',SECRET).update(p[0]).digest('hex');if(p[1].length!==e.length||!crypto.timingSafeEqual(Buffer.from(p[1]),Buffer.from(e)))return null;return p[0];}
function admin(req){const raw=verify((req.headers.cookie||'').match(/jg_session=([^;]+)/)?.[1]);if(!raw)return null;const a=db.prepare('SELECT s.admin_id,s.expires_at,a.username FROM sessions s JOIN admins a ON a.id=s.admin_id WHERE s.token_hash=?').get(sha(raw));if(!a||a.expires_at<Date.now())return null;return a;}
function requireAdmin(req,res,next){const a=admin(req);if(!a)return res.status(401).json({error:'Unauthorized'});req.admin=a;next();}
function csrf(req,res,next){if(['GET','HEAD','OPTIONS'].includes(req.method))return next();const a=admin(req);if(!a)return res.status(401).json({error:'Unauthorized'});const expected=crypto.createHmac('sha256',SECRET).update(String(a.admin_id)).digest('hex');const got=String(req.headers['x-csrf-token']||'');if(got.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(got),Buffer.from(expected)))return res.status(403).json({error:'CSRF check failed'});next();}
function clean(v,max=300){return String(v??'').trim().slice(0,max)}function int(v,min=0){const n=Number(v);return Number.isInteger(n)&&n>=min?n:null}function slug(v){return clean(v,80).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function publicProduct(r){return {...r,final_price:Math.round(r.price*(100-r.discount)/100),in_stock:r.stock>0};}
app.get('/api/categories',apiLimiter,(req,res)=>res.json(db.prepare('SELECT id,name,slug,image FROM categories WHERE active=1 ORDER BY name').all()));
app.get('/api/products',apiLimiter,(req,res)=>{const {q='',category='',min='',max='',sale=''}=req.query;let sql=`SELECT p.*,c.name category FROM products p JOIN categories c ON c.id=p.category_id WHERE p.active=1 AND c.active=1`;const args=[];if(q){sql+=' AND (p.name LIKE ? OR p.description LIKE ? OR c.name LIKE ?)';const x='%'+clean(q,80)+'%';args.push(x,x,x)}if(category){sql+=' AND c.slug=?';args.push(clean(category,80))}if(min!==''){const n=int(min);if(n!==null){sql+=' AND p.price>=?';args.push(n)}}if(max!==''){const n=int(max);if(n!==null){sql+=' AND p.price<=?';args.push(n)}}if(sale==='1')sql+=' AND p.discount>0';sql+=' ORDER BY p.id DESC';res.json(db.prepare(sql).all(...args).map(publicProduct));});
app.get('/api/products/:id',apiLimiter,(req,res)=>{const r=db.prepare(`SELECT p.*,c.name category,c.slug category_slug FROM products p JOIN categories c ON c.id=p.category_id WHERE p.id=? AND p.active=1`).get(Number(req.params.id));if(!r)return res.status(404).json({error:'Product not found'});res.json(publicProduct(r));});
app.post('/api/login',loginLimiter,(req,res)=>{const u=clean(req.body?.username,80),p=String(req.body?.password||'');const a=db.prepare('SELECT id,username,password_hash FROM admins WHERE username=?').get(u);if(!a||!bcrypt.compareSync(p,a.password_hash))return res.status(401).json({error:'Invalid login'});const raw=crypto.randomBytes(32).toString('hex');db.prepare('DELETE FROM sessions WHERE expires_at<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(sha(raw),a.id,Date.now()+8*60*60*1000);const token=crypto.createHmac('sha256',SECRET).update(String(a.id)).digest('hex');
res.setHeader(
  'Set-Cookie',
  `jg_session=${sign(raw)}; HttpOnly${secureCookie}; SameSite=Lax; Path=/; Max-Age=28800`
);res.json({ok:true,username:a.username,csrfToken:token});});
app.get('/api/admin/me',requireAdmin,(req,res)=>res.json({username:req.admin.username,csrfToken:crypto.createHmac('sha256',SECRET).update(String(req.admin.admin_id)).digest('hex')}));
app.post('/api/logout',csrf,(req,res)=>{const raw=verify((req.headers.cookie||'').match(/jg_session=([^;]+)/)?.[1]);if(raw)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(sha(raw));res.setHeader(
  'Set-Cookie',
  `jg_session=; HttpOnly${secureCookie}; SameSite=Lax; Path=/; Max-Age=0`
);res.json({ok:true});});
function validateProduct(body){const name=clean(body.name,120),size=clean(body.size,40),description=clean(body.description,1000),category_id=int(body.category_id,1),price=int(body.price,0),stock=int(body.stock,0),discount=int(body.discount,0);if(!name||!size||!category_id||price===null||stock===null||discount===null||discount>100)return null;const cat=db.prepare('SELECT id FROM categories WHERE id=? AND active=1').get(category_id);if(!cat)return null;return {name,size,description,category_id,price,stock,discount,image:clean(body.image,500),icon:clean(body.icon||'🛒',8)};}
app.get('/api/admin/products',requireAdmin,(req,res)=>res.json(db.prepare(`SELECT p.*,c.name category FROM products p JOIN categories c ON c.id=p.category_id ORDER BY p.id DESC`).all().map(publicProduct)));
app.post('/api/admin/products',csrf,(req,res)=>{const v=validateProduct(req.body||{});if(!v)return res.status(400).json({error:'Invalid product data'});const r=db.prepare('INSERT INTO products(name,size,category_id,description,price,stock,discount,image,icon) VALUES(?,?,?,?,?,?,?,?,?)').run(v.name,v.size,v.category_id,v.description,v.price,v.stock,v.discount,v.image,v.icon);res.status(201).json({id:r.lastInsertRowid});});
app.put('/api/admin/products/:id',csrf,(req,res)=>{const v=validateProduct(req.body||{}),id=int(req.params.id,1);if(!v||!id)return res.status(400).json({error:'Invalid product data'});const r=db.prepare('UPDATE products SET name=?,size=?,category_id=?,description=?,price=?,stock=?,discount=?,image=?,icon=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(v.name,v.size,v.category_id,v.description,v.price,v.stock,v.discount,v.image,v.icon,id);if(!r.changes)return res.status(404).json({error:'Product not found'});res.json({ok:true});});
app.delete('/api/admin/products/:id',csrf,(req,res)=>{const id=int(req.params.id,1);if(!id)return res.status(400).json({error:'Invalid id'});const r=db.prepare('UPDATE products SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(id);if(!r.changes)return res.status(404).json({error:'Product not found'});res.json({ok:true});});
app.get('/api/admin/categories',requireAdmin,(req,res)=>res.json(db.prepare('SELECT * FROM categories ORDER BY name').all()));
app.post('/api/admin/categories',csrf,(req,res)=>{const name=clean(req.body?.name,80);if(!name)return res.status(400).json({error:'Category name required'});try{const r=db.prepare('INSERT INTO categories(name,slug,image) VALUES(?,?,?)').run(name,slug(name),clean(req.body?.image,500));res.status(201).json({id:r.lastInsertRowid});}catch(e){res.status(409).json({error:'Category already exists'});}});
app.put('/api/admin/categories/:id',csrf,(req,res)=>{const id=int(req.params.id,1),name=clean(req.body?.name,80);if(!id||!name)return res.status(400).json({error:'Invalid category'});try{const r=db.prepare('UPDATE categories SET name=?,slug=?,image=? WHERE id=?').run(name,slug(name),clean(req.body?.image,500),id);if(!r.changes)return res.status(404).json({error:'Category not found'});res.json({ok:true});}catch(e){res.status(409).json({error:'Category already exists'});}});
app.delete('/api/admin/categories/:id',csrf,(req,res)=>{const id=int(req.params.id,1);const used=db.prepare('SELECT COUNT(*) n FROM products WHERE category_id=? AND active=1').get(id).n;if(used)return res.status(409).json({error:'Category has active products'});const r=db.prepare('UPDATE categories SET active=0 WHERE id=?').run(id);if(!r.changes)return res.status(404).json({error:'Category not found'});res.json({ok:true});});
app.get('/api/admin/orders',requireAdmin,(req,res)=>res.json(db.prepare('SELECT * FROM orders ORDER BY id DESC').all()));
app.get('/api/admin/orders/:id',requireAdmin,(req,res)=>{const o=db.prepare('SELECT * FROM orders WHERE id=?').get(int(req.params.id,1));if(!o)return res.status(404).json({error:'Order not found'});o.items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(o.id);res.json(o);});
app.patch('/api/admin/orders/:id',csrf,(req,res)=>{const allowed=['Pending','Confirmed','Processing','Out for Delivery','Completed','Cancelled'];const status=clean(req.body?.status,30);if(!allowed.includes(status))return res.status(400).json({error:'Invalid status'});const o=db.prepare('SELECT status FROM orders WHERE id=?').get(int(req.params.id,1));if(!o)return res.status(404).json({error:'Order not found'});const tx=db.transaction(()=>{if(status==='Cancelled'&&o.status!=='Cancelled'){const items=db.prepare('SELECT product_id,quantity FROM order_items WHERE order_id=?').all(req.params.id);const add=db.prepare('UPDATE products SET stock=stock+?,updated_at=CURRENT_TIMESTAMP WHERE id=?');items.forEach(i=>add.run(i.quantity,i.product_id));}db.prepare('UPDATE orders SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(status,req.params.id);});tx();res.json({ok:true});});
app.get('/api/admin/stats',requireAdmin,(req,res)=>{const products=db.prepare('SELECT COUNT(*) n FROM products WHERE active=1').get().n,low=db.prepare('SELECT COUNT(*) n FROM products WHERE active=1 AND stock<=5').get().n,orders=db.prepare('SELECT COUNT(*) n FROM orders').get().n,revenue=db.prepare("SELECT COALESCE(SUM(total),0) n FROM orders WHERE status!='Cancelled'").get().n;res.json({products,low,orders,revenue});});
function orderNo(){return 'JG-'+new Date().toISOString().slice(0,10).replace(/-/g,'')+'-'+crypto.randomBytes(3).toString('hex').toUpperCase();}
app.post('/api/orders',apiLimiter,(req,res)=>{const name=clean(req.body?.customer_name,120),phone=clean(req.body?.phone,30),address=clean(req.body?.address,300),city=clean(req.body?.city,80),notes=clean(req.body?.notes,500),payment=clean(req.body?.payment_method||'Cash on Delivery',40),items=Array.isArray(req.body?.items)?req.body.items:[];if(!name||!phone||!address||!city||!items.length)return res.status(400).json({error:'Please complete customer details and cart'});const normalized=items.map(x=>({id:int(x.id,1),quantity:int(x.quantity,1)}));if(normalized.some(x=>!x.id||!x.quantity))return res.status(400).json({error:'Invalid cart'});const tx=db.transaction(()=>{let subtotal=0,discount=0;const rows=[];for(const i of normalized){const p=db.prepare(`SELECT p.*,c.name category FROM products p JOIN categories c ON c.id=p.category_id WHERE p.id=? AND p.active=1`).get(i.id);if(!p)throw new Error('PRODUCT_NOT_FOUND');if(i.quantity>p.stock)throw new Error('STOCK:'+p.name);const line=Math.round(p.price*(100-p.discount)/100)*i.quantity;subtotal+=line;discount+=Math.round(p.price*p.discount/100)*i.quantity;rows.push({p,i,line});}const delivery=subtotal>=5000?0:300;const total=subtotal+delivery;let no=orderNo();while(db.prepare('SELECT 1 FROM orders WHERE order_no=?').get(no))no=orderNo();const r=db.prepare('INSERT INTO orders(order_no,customer_name,phone,address,city,notes,subtotal,discount,delivery_fee,total,payment_method) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(no,name,phone,address,city,notes,subtotal,discount,delivery,total,payment);const oi=db.prepare('INSERT INTO order_items(order_id,product_id,product_name,size,unit_price,quantity,line_total) VALUES(?,?,?,?,?,?,?)');const dec=db.prepare('UPDATE products SET stock=stock-?,updated_at=CURRENT_TIMESTAMP WHERE id=?');rows.forEach(x=>{oi.run(r.lastInsertRowid,x.p.id,x.p.name,x.p.size,Math.round(x.p.price*(100-x.p.discount)/100),x.i.quantity,x.line);dec.run(x.i.quantity,x.p.id)});return {orderId:r.lastInsertRowid,orderNo:no,subtotal,discount,delivery,total};});try{res.status(201).json(tx());}catch(e){if(e.message==='PRODUCT_NOT_FOUND')return res.status(400).json({error:'A product is no longer available'});if(e.message.startsWith('STOCK:'))return res.status(409).json({error:`Not enough stock for ${e.message.slice(6)}`});console.error(e);res.status(500).json({error:'Could not place order'});}});
app.get('/api/orders/:orderNo',apiLimiter,(req,res)=>{const o=db.prepare('SELECT order_no,customer_name,phone,address,city,subtotal,discount,delivery_fee,total,status,payment_method,created_at FROM orders WHERE order_no=?').get(clean(req.params.orderNo,40));if(!o)return res.status(404).json({error:'Order not found'});o.items=db.prepare('SELECT product_name,size,unit_price,quantity,line_total FROM order_items WHERE order_id=(SELECT id FROM orders WHERE order_no=?)').all(o.order_no);res.json(o);});
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));
app.use((req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'Not found'});res.sendFile(path.join(__dirname,'public','index.html'));});
app.listen(PORT,()=>console.log(`Jayanthi Grocery running on http://localhost:${PORT}`));
